user:
  maximum_name: 50
  maximum_email: 255
  minimum_pass: 6
  size: 50
  sizeuser: 80
  reset: 2
remember:
  ischeck: "1"
micropost:
  maximum: 140
  pic_size: 5
  file_type: "image/jpeg,image/gif,image/png"

